### ISSUE TITLE
Fiddler4 Telerik / raw http request 

### ISSUE THREAD

**Issue by devorel** [kevinswiber/postman2openapi#45]
Hi  
Can you add support with Fiddler4 Telerik / raw http request ? 

```http request
GET http://fiddler2.com/content/GetBanner?clientId=s1 HTTP/1.1
Host: fiddler2.com
Connection: Keep-Alive
```

```http request
POST http://fiddler2.com/content/GetBanner?clientId=s2 HTTP/1.1
Host: fiddler2.com
Connection: Keep-Alive

{data:123}
```

**Comment by kevinswiber** [comment]
Hi there.  Can you clarify this request?  What would supporting Fiddler look like in this library?

**Comment by devorel** [comment]
HI 
For example (https://kevinswiber.github.io/postman2openapi/)
in the page you can paste some text and get it as openapi .
i want to paste a full list of http request , and get it as openapi .

**Comment by devorel** [comment]
GET http://fiddler2.com/content/GetBanner?clientId=s1 HTTP/1.1
Host: fiddler2.com
Connection: Keep-Alive


POST http://fiddler2.com/content/GetBanner?clientId=s2 HTTP/1.1
Host: fiddler2.com
Connection: Keep-Alive

{data:123}

**Comment by kevinswiber** [comment]
I think this would be a different codebase entirely.  This project is only concerned with converting Postman Collections to OpenAPI definitions.
