### ISSUE TITLE
`just build` does not build nodejs target

### ISSUE THREAD

**Issue by bryancross** [kevinswiber/postman2openapi#71]
[README](https://github.com/kevinswiber/postman2openapi#just-build) says `just build` builds all targets, however it doesn't appear to build the `nodejs` target.  `just build-nodejs` does however.  Also, it might be worth noting that `wasm` must be installed to run this target.  

I am barely able to spell Rust so it is very likely this an issue with me and not the repo.

**Comment by kevinswiber** [comment]
Thank you.  I clarified the language in the README and added `just prepare` to build all assets and run tests.

https://github.com/kevinswiber/postman2openapi#just-prepare
