### ISSUE TITLE
Node transpile function is not maintaining put bodies

### ISSUE THREAD

**Issue by ScriptAlchemist** [kevinswiber/postman2openapi#80]
I'm building an api that is using a postman schema as the base. We transpile it to openapi spec to allow for an autogenerated webpage. I noticed that in the transpilation. That the Update routes have no bodies in them

There are bodies in the postman 
<img width="768" alt="image" src="https://github.com/user-attachments/assets/9d554c53-5262-466f-a833-b7645ba3661e">

Which don't seem to make it after the transpile.

<img width="767" alt="image" src="https://github.com/user-attachments/assets/61e5347a-f042-4ddd-b26c-cc0f8801a162">

<img width="619" alt="image" src="https://github.com/user-attachments/assets/71368629-067f-4bb9-b9e4-9afe790dd3f5">

Compared to the post routes that seem to fill out the schema after the transpiling.

<img width="446" alt="image" src="https://github.com/user-attachments/assets/2b7bd30d-7b6a-4cb9-80bf-96e4ed7765b2">

**Comment by ScriptAlchemist** [comment]
My easy fix. You just be to take all the puts and replace the parameters with a similar body for the posts. 

I'd much rather not add more complexity to the next person. If I don't have to.

So I'd appreciate if anyone knows what I'm doing wrong. Maybe this is a bug or maybe it's functioning correctly and I just don't understand.

**Comment by ScriptAlchemist** [comment]
My current solution is to just take the transpiled code and placing the parameters from the post route into the put routes. It's working now. So I won't really be worried about this for now.

**Comment by kevinswiber** [comment]
@ScriptAlchemist For the request in Postman, make sure you're selecting "JSON" as the type, save it, and try again. Also, make sure the request doesn't have an example with an empty request body.  I don't remember if I implemented request body schema merging in that scenario.

<img width="350" alt="image" src="https://github.com/user-attachments/assets/a1aa8f52-ef0e-41ac-8e3c-169aeb172e4d">

**Comment by ScriptAlchemist** [comment]
@kevinswiber So I had one example where it was sending an empty object. On purpose because it's supposed to have it fail based on validation.

So adding in a json object seems to make it work. Thanks. 

I'm not sure if that's the better solution though. Cause inside of the postman doc that I give others. It's going to have a technically incorrect example. So maybe I'll just programmatically delete it after 
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/e26e365f-3465-404f-bb6b-2db2a1c058f6">
